// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using statusservice.Data;
using System;

namespace statusservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171228112948_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("statusservice.Model.ContextStatus", b =>
                {
                    b.Property<int>("contextStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("context")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("contextDescription")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("endTimestampTicks");

                    b.Property<long>("startTimestampTicks");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("thingStatusId");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("contextStatusId");

                    b.HasIndex("thingStatusId");

                    b.ToTable("ContextStatus");
                });

            modelBuilder.Entity("statusservice.Model.ThingStatus", b =>
                {
                    b.Property<int>("thingStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("thingId")
                        .IsRequired();

                    b.HasKey("thingStatusId");

                    b.ToTable("ThingStatus");
                });

            modelBuilder.Entity("statusservice.Model.ContextStatus", b =>
                {
                    b.HasOne("statusservice.Model.ThingStatus")
                        .WithMany("statusContexts")
                        .HasForeignKey("thingStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
